test29/urls.py
from django.contrib import admin
from django.urls import path

from quiz import views as quiz_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', quiz_views.homepage, name='homepage'),
    path('quiz/answer', quiz_views.answer, name='answer'),
    path('quiz/create', quiz_views.create, name='create'),
    path('quiz/statistics', quiz_views.statistic, name='create')
]

quiz/models.py
from django.db import models

# Create your models here.

class Quiz(models.Model):
    question = models.TextField()
    answer = models.BooleanField()
    correct = models.IntegerField(default=0)
    incorrect = models.IntegerField(default=0)

quiz/views.py
from django.shortcuts import render, redirect
from .models import Quiz

# Create your views here.

def homepage(request):
    return render(request, 'homepage.html')

def create(request):
    if request.POST:
        if request.POST['answer'] == 'yes':
            answer = True
        else:
            answer = False
        Quiz.objects.create(question=request.POST['question'], 
                answer=answer)
        return redirect('/')
    return render(request, 'create.html')

def answer(request):
    quiz_list = Quiz.objects.all()
    if request.POST:
        score = 0
        for i in range(1, len(request.POST)):
            quiz = Quiz.objects.get(pk=i)
            if request.POST['answer_' + str(i)] == 'yes':
                answer = True
            else:
                answer = False
            if quiz.answer is answer:
                quiz.correct += 1
                score += 1
            else:
                quiz.incorrect += 1
            quiz.save()
        return render(request, 'answer.html', {'quiz_list': quiz_list, 'score': score})
    return render(request, 'answer.html', {'quiz_list': quiz_list})

def statistic(request):
    quiz_list = Quiz.objects.all()
    return render(request, 'statistic.html', {'quiz_list': quiz_list})

quiz/templates/answer.html
<html>
	<head>
		<title>Is this a quiz?</title>
	</head>
	<body>
		<h1>Questions</h1>
		<form method='POST' action='/quiz/answer'>
			{% csrf_token %}
			{% for quiz in quiz_list %}
			<p id={{ forloop.counter0 }}>{{ quiz.id }}. {{ quiz.question }} </p>
			<input type='radio' id='id_yes_{{ forloop.counter0 }}'
			       name='answer_{{ quiz.id }}'
			       value='yes'>Yes</input>
			<input type='radio' id='id_no_{{ forloop.counter0 }}'
			       name='answer_{{ quiz.id }}'
			       value='no'>No</input>
		{% endfor %}
		<br><br><input type='submit' id='id_submit' value='submit'/>
		<br>
		</form>
		{% if score %}
		    <h2>Your score is {{ score }}.</h2>
		   {% endif %}
                <form action="/"><input type="submit" id='id_back' value="back" /></form>
	</body>
</html>

quiz/templates/create.html
<html>
	<head>
		<title>create a question</title>
	</head>
	<body>
		<form method='POST' action='/quiz/create'>
			{% csrf_token %}
			Question: <input type='text' id='id_question' name='question'/><br>
			Answer: <input type='radio' id='id_yes' name='answer' value='yes' >Yes</input>
			<input type='radio' id='id_no' name='answer' value='no' >No</input>
			<input type='submit' id='id_submit' value='submit'/>
		</form>
		<br>
		<form action="/"><input type="submit" id='id_back' value="back" /></form>
	</body>
</html>

quiz/templates/homepage.html
<html>
	<head>
		<title>Answer or Question</title>
	</head>
	<body>
		<form action="quiz/create"><input type="submit" id='id_create' value="create question" /></form>
		<form action="quiz/answer"><input type="submit" id='id_answer' value="go to answer" /></form>
		<form action="quiz/statistics"><input type="submit" id='id_statistics' value="statistics" /></form>
	</body>
</html>

quiz/templates/statistic.html
<html>
  <head>
    <title>Is this a statistics?</title>
  </head>
  <body>
    <h1>Statistics</h1>
    <table id="id_quiz_statistics" style="width:66%" border="1">
      <tr><th>Question</th><th>Correct</th> <th>incorrect</th></tr>
      {% for quiz in quiz_list %}
      <tr>
	<td>{{ forloop.counter }}: {{ quiz.question }}</td>
	<td>{{ quiz.correct }}</td>
	<td>{{ quiz.incorrect }}</td>
      </tr>       
      {% endfor %}
    </table>
    <form action="/"><input type="submit" id='id_back' value="back" /></form>
  </body>
</html>